apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  mapRoles: |
    - rolearn: arn:aws:iam::767828742018:role/${var.project_name}-eks-unified-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::767828742018:role/${var.project_name}-eks-unified-role
      username: eks-admin
      groups:
        - system:masters


# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: aws-auth
#   namespace: kube-system
# data:
#   mapRoles: |
#     - rolearn: arn:aws:iam::767828742018:role/eks_role
#       username: terraform
#       groups:
#         - system:masters
